/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module circuito_casa (
  input P,
  input F1,
  input F2,
  input L,
  output C1,
  output C2,
  output CE,
  output B,
  output SL,
  output SRE
);
  wire s0;
  assign s0 = ~ P;
  assign C1 = (~ F1 & F2 & s0);
  assign CE = ((F1 & s0) | (F2 & s0));
  assign C2 = P;
  assign B = F2;
  assign SL = L;
  assign SRE = F1;
endmodule
